import './index.css'
import { Nav } from './components/navbar'
import ReduxProvider from './providers/redux-provider';
import { PostContextProvider } from './providers/postContext';
import { Fira_Sans } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const firaSans = Fira_Sans({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.className}!bg-blue- h-fit !max-w-screen w-screen overflow-y-scroll overflow-x-clip`}
      >
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />

        <ReduxProvider>
          <PostContextProvider>
            <Nav />
            {children}
          </PostContextProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
