import Nav from "./components/navbar.jsx";
import ReduxProvider from "../providers/redux-provider";
// import { Fira_Sans } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const firaSans = Fira_Sans({
//   weight: ["400", "700"],
//   subsets: ["latin"],
//   display: "swap",
// });

export default function AdminLayout({ children }) {
  return (
   
      <div className={` !bg-white !h-full `}>
       
          <Nav />
          {children}
      
      </div>
    
  );
}
